### ISSUE TITLE
finite_temperature_ground_state

### ISSUE THREAD

**Issue by HamidArianZad** [joselado/dmrgpy#22]
Dear Jose,

I am investigating the magnetization of a transverse field  Ising model at low temperature by using dmrg form dmrgpy.
I found two folders in examples of dmrgpy package. 
I have some questions and I appreciate if you reply. 
- You considered `mode="ED"`, can I switch the mode to `mode="dmrg"`?
- If I consider `T = 0.1`, should I multiply this value with some number to get the input temperature value of the dmrg calculations? Or the considered temperature value (`T = 0.1`) is the same as the input temperature of dmrg calculations?
For example, in main.py file in folder "finite_temperature_dynamical_correlator" you considered `T=0.0005` for dmrg calculations (line 30), while for plotting the dynamical correlators you nominated the temperature as `T = 0.1` (line 50).
On the other hand, in main.py file in folder "finite_temperature_ground_state", you considered the temperature as `T = 0.01` (line 24).

**Comment by joselado** [comment]
Dear Hamid,

currently finite temperature calculations only work with ED (the DMRG version is still under development). The temperature has natural units (namely, the same as the units of the Hamiltonian).

Overall, since finite-temperature calculations are not fully benchmarked, my suggestion would be to not use dmrgpy for them, as unfortunately this has not been finished yet.

Best regards,
Jose
